name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.15.6 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish library
        run: |
          sed -i "s#\"version\": \"0.0.0\"#\"version\": \"${TAG_NAME}\"#" ./packages/ui/package.json
          cd packages/ui
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Verify npm publish
        run: echo "Npm publish completed successfully."
